### include find path #####################################

INCPATH += -I$(XSYSTEM_DIR)/
INCPATH += -I$(XSYSTEM_DIR)/LinkList
INCPATH += -I$(XSYSTEM_DIR)/utils

### object file ###############################################

OBJECTS += $(XSYSTEM_DIR)/utils/err.o