XSYSTEM_DIR	= ..

CC_PREX = 

### include find path ###############################

INCPATH = -I.

### object file #####################################

OBJECTS = array_test.o array.o

### compile target ###################################

TARGET = array_test

all: $(TARGET)

include Makefile.components
include $(XSYSTEM_DIR)/Makefile.include
