XSYSTEM_DIR	= ..

CC_PREX = 

### include find path ###############################

INCPATH = -I.

### object file #####################################

OBJECTS = main.o LinkList.o

### compile target ###################################

TARGET = LinkList_test

all: $(TARGET)

include Makefile.components
include $(XSYSTEM_DIR)/Makefile.include
