XSYSTEM_DIR	= ..

CC_PREX = 

### include find path ###############################

INCPATH = -I.

### object file #####################################

OBJECTS = stack_test.o stack.o

### compile target ###################################

TARGET = stack_test

all: $(TARGET)

include Makefile.components
include $(XSYSTEM_DIR)/Makefile.include
