XSYSTEM_DIR	= ..

CC_PREX = 

### include find path ###############################

INCPATH = -I.

### object file #####################################

OBJECTS = SeqQueue_test.o SeqQueue.o

### compile target ###################################

TARGET = SeqQueue_test

all: $(TARGET)

include Makefile.components
include $(XSYSTEM_DIR)/Makefile.include
